spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:postgres}:${PG_PORT:5432}/${PG_DATABASE:user_db}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: filesystem:/app/database/migrations

app:
  swagger:
    gateway-url: http://localhost:8180
    user-service-url: http://localhost:8181

server:
  port: 8081